"""initial schema

Revision ID: 2ae930654675
Revises: 
Create Date: 2026-05-28 02:41:12.538887+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '2ae930654675'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'setter', 'member', name='role'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'banned', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('target_kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sa.Enum('live', 'virtual', name='contestmode'), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('freeze_last_min', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('statement_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_format_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_format_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('constraints_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('scoring_mode', sa.Enum('ioi_strict', 'partial', name='scoringmode'), nullable=False),
    sa.Column('python_time_multiplier', sa.Float(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_is_public'), 'problems', ['is_public'], unique=False)
    op.create_index('ix_problems_search', 'problems', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=True)
    op.create_table('contest_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'user_id')
    )
    op.create_index(op.f('ix_contest_participants_contest_id'), 'contest_participants', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contest_participants_user_id'), 'contest_participants', ['user_id'], unique=False)
    op.create_table('contest_problems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'ord'),
    sa.UniqueConstraint('contest_id', 'problem_id')
    )
    op.create_index(op.f('ix_contest_problems_contest_id'), 'contest_problems', ['contest_id'], unique=False)
    op.create_table('problem_topics',
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'topic_id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('contest_id', sa.Uuid(), nullable=True),
    sa.Column('language', sa.Enum('cpp', 'python', name='language'), nullable=False),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'judging', 'done', 'error', name='submissionstatus'), nullable=False),
    sa.Column('overall_verdict', sa.Enum('ac', 'wa', 'tle', 'mle', 're', 'ce', 'ie', 'skipped', name='verdict'), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('max_time_ms', sa.Integer(), nullable=False),
    sa.Column('max_memory_kb', sa.Integer(), nullable=False),
    sa.Column('compile_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('judged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submissions_created', 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_user_problem', 'submissions', ['user_id', 'problem_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'ord')
    )
    op.create_index(op.f('ix_subtasks_problem_id'), 'subtasks', ['problem_id'], unique=False)
    op.create_table('user_problem_best',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=False),
    sa.Column('first_full_score_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'problem_id')
    )
    op.create_table('testcases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subtask_id', sa.Uuid(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('input_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_in_bytes', sa.Integer(), nullable=False),
    sa.Column('size_out_bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtask_id', 'ord')
    )
    op.create_index(op.f('ix_testcases_subtask_id'), 'testcases', ['subtask_id'], unique=False)
    op.create_table('submission_testcases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('testcase_id', sa.Uuid(), nullable=False),
    sa.Column('subtask_id', sa.Uuid(), nullable=False),
    sa.Column('judge0_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verdict', sa.Enum('ac', 'wa', 'tle', 'mle', 're', 'ce', 'ie', 'skipped', name='verdict'), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('stderr_excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'testcase_id')
    )
    op.create_index(op.f('ix_submission_testcases_submission_id'), 'submission_testcases', ['submission_id'], unique=False)
    # ### end Alembic commands ###

    # FTS trigger: maintain problems.search_vector (title A, statement B, constraints C).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION problems_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector('english', coalesce(NEW.title, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(NEW.statement_md, '')), 'B') ||
                setweight(to_tsvector('english', coalesce(NEW.constraints_md, '')), 'C');
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER problems_search_vector_trg
        BEFORE INSERT OR UPDATE OF title, statement_md, constraints_md ON problems
        FOR EACH ROW EXECUTE FUNCTION problems_search_vector_update();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS problems_search_vector_trg ON problems;")
    op.execute("DROP FUNCTION IF EXISTS problems_search_vector_update();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_testcases_submission_id'), table_name='submission_testcases')
    op.drop_table('submission_testcases')
    op.drop_index(op.f('ix_testcases_subtask_id'), table_name='testcases')
    op.drop_table('testcases')
    op.drop_table('user_problem_best')
    op.drop_index(op.f('ix_subtasks_problem_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index('ix_submissions_user_problem', table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index('ix_submissions_created', table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('problem_topics')
    op.drop_index(op.f('ix_contest_problems_contest_id'), table_name='contest_problems')
    op.drop_table('contest_problems')
    op.drop_index(op.f('ix_contest_participants_user_id'), table_name='contest_participants')
    op.drop_index(op.f('ix_contest_participants_contest_id'), table_name='contest_participants')
    op.drop_table('contest_participants')
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_index('ix_problems_search', table_name='problems', postgresql_using='gin')
    op.drop_index(op.f('ix_problems_is_public'), table_name='problems')
    op.drop_table('problems')
    op.drop_table('contests')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('topics')
    # ### end Alembic commands ###
