"""sample subtasks

Revision ID: 1ecdd5ae6119
Revises: 6fedb580889c
Create Date: 2026-05-28 03:57:02.104482+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '1ecdd5ae6119'
down_revision: Union[str, None] = '6fedb580889c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('is_sample', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('testcases', sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testcases', 'explanation')
    op.drop_column('subtasks', 'is_sample')
    # ### end Alembic commands ###
