"""user username school

Revision ID: 3cc46657c3cb
Revises: 1ecdd5ae6119
Create Date: 2026-05-28 04:33:16.787727+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '3cc46657c3cb'
down_revision: Union[str, None] = '1ecdd5ae6119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', postgresql.CITEXT(), nullable=True))
    op.add_column('users', sa.Column('school', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'school')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
